kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: "anything"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
